### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by YunusEmreAlps** [CaliCastle/cali-fm#3]
Hello,

I hope you're well and everything is good with you.

When I use this repo for RSS Feed(https://github.com/timdorr/spotifeed) app not working. Where do I need to get the RSS Feed?  

Thank you very much.
Best regards,

**Comment by CaliCastle** [comment]
Hi @YunusEmreAlps!

Can you provide the RSS URL so I can take a look? And what do you mean exactly by "the app is not working"?

Assuming you have a valid RSS feed from a podcast (e.g. https://lexfridman.com/feed/podcast )

**Comment by YunusEmreAlps** [comment]
Hi @CaliCastle

The app is working great with default values. Actually when I changed to use my own RSS not work. I guess my RSS is not valid. 

This is my RSS: https://spotifeed.timdorr.com/3WnbvkFzYerPE1OPl0AEQh

Thank You!

**Comment by CaliCastle** [comment]
> Hi @CaliCastle
> 
> The app is working great with default values. Actually when I changed to use my own RSS not work. I guess my RSS is not valid.
> 
> This is my RSS: https://spotifeed.timdorr.com/3WnbvkFzYerPE1OPl0AEQh
> 
> Thank You!

@YunusEmreAlps 
It doesn't look like the RSS URL you provided has direct audio files, which is usually wrapped within `enclosure` of some sort.

We'd need a valid RSS that has audio files in order to play the episodes correctly.
