### ISSUE TITLE
Cannot read properties of null (reading 'title')

### ISSUE THREAD

**Issue by zacfire** [CaliCastle/cali-fm#4]
Unhandled Runtime Error
Error: Cannot read properties of null (reading 'title')，and this is rss：https://feed.xyzfm.space/cu4uwhht96nv

**Comment by CaliCastle** [comment]
https://github.com/CaliCastle/cali-fm/assets/10830749/1e07fc88-0f07-481b-860b-6f1a406cd78e

I've tried testing with your RSS and it works properly.
